version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: face_postgres
    restart: always
    environment:
      POSTGRES_DB: face_db
      POSTGRES_USER: face_user
      POSTGRES_PASSWORD: face_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
